### ISSUE TITLE
Authorization and SQL 

### ISSUE THREAD

**Issue by Sequential-circuits** [lattebank/airflow-dag-creation-manager-plugin#13]
Please note that unless you use this versions you will run into authorization (flask-login) and incompatibility (flask) issues
pip install flask==0.12.4
pip install flask-login==0.3.2

Also, there seems to be a bug with the SQL command when running upgradedb.py 

_019-02-13 12:35:37,238] {dag_converter.py:32} INFO - loading dag template: dag_code
[2019-02-13 12:35:37,329] {models.py:71} WARNING - Run python {AIRFLOW_HOME}/plugins/dcmp/tools/upgradedb.py first
sql:

        CREATE TABLE IF NOT EXISTS `dcmp_dag` (
          `id` int(11) NOT NULL AUTO_INCREMENT,
          `dag_name` varchar(250) NOT NULL,
          `version` int(11) NOT NULL,
          `category` varchar(50) NOT NULL,
          `editing` tinyint(1) NOT NULL,
          `editing_user_id` int(11) DEFAULT NULL,
          `editing_user_name` varchar(250) DEFAULT NULL,
          `last_editor_user_id` int(11) DEFAULT NULL,
          `last_editor_user_name` varchar(250) DEFAULT NULL,
          `updated_at` datetime(6) NOT NULL,
          PRIMARY KEY (`id`),
          UNIQUE KEY `dag_name` (`dag_name`),
          KEY `category` (`category`),
          KEY `editing` (`editing`),
          KEY `updated_at` (`updated_at`)
        ) DEFAULT CHARSET=utf8mb4;

Traceback (most recent call last):
  File "/root/airflow/plugins/dcmp/tools/upgradedb.py", line 130, in <module>
    main()
  File "/root/airflow/plugins/dcmp/tools/upgradedb.py", line 122, in main
    run_version_0_0_1()
  File "/root/airflow/plugins/dcmp/tools/upgradedb.py", line 50, in run_version_0_0_1
    """)
  File "/root/airflow/plugins/dcmp/tools/upgradedb.py", line 25, in run_sql
    raise e
TypeError: connect() argument 2 must be string, not None_

**Comment by ericlsimplifi** [comment]
got the same error. any resolution?

**Comment by deckmon** [comment]
your may try to run sql by yourself

``` sql
CREATE TABLE `dcmp_dag` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `dag_name` varchar(250) NOT NULL,
  `version` int(11) NOT NULL,
  `category` varchar(50) NOT NULL,
  `editing` tinyint(1) NOT NULL,
  `editing_user_id` int(11) DEFAULT NULL,
  `editing_user_name` varchar(250) DEFAULT NULL,
  `last_editor_user_id` int(11) DEFAULT NULL,
  `last_editor_user_name` varchar(250) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `editing_start` datetime(6) DEFAULT NULL,
  `last_edited_at` datetime(6) DEFAULT NULL,
  `approved_version` int(11) NOT NULL,
  `approver_user_id` int(11) DEFAULT NULL,
  `approver_user_name` varchar(250) DEFAULT NULL,
  `last_approved_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `dag_name` (`dag_name`),
  KEY `category` (`category`),
  KEY `editing` (`editing`),
  KEY `updated_at` (`updated_at`),
  KEY `editing_start` (`editing_start`),
  KEY `last_edited_at` (`last_edited_at`),
  KEY `approved_version` (`approved_version`),
  KEY `last_approved_at` (`last_approved_at`),
  KEY `idx_updated_at` (`updated_at`)
) ENGINE=InnoDB CHARSET=utf8mb4;

CREATE TABLE `dcmp_dag_conf` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `dag_id` int(11) NOT NULL,
  `dag_name` varchar(250) NOT NULL,
  `action` varchar(50) NOT NULL,
  `version` int(11) NOT NULL,
  `conf` mediumtext NOT NULL,
  `creator_user_id` int(11) DEFAULT NULL,
  `creator_user_name` varchar(250) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `approver_user_id` int(11) DEFAULT NULL,
  `approver_user_name` varchar(250) DEFAULT NULL,
  `approved_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `dag_id` (`dag_id`),
  KEY `dag_name` (`dag_name`),
  KEY `action` (`action`),
  KEY `version` (`version`),
  KEY `created_at` (`created_at`),
  KEY `approved_at` (`approved_at`)
) ENGINE=InnoDB CHARSET=utf8mb4;

CREATE TABLE `dcmp_user_profile` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `is_superuser` tinyint(1) NOT NULL,
  `is_data_profiler` tinyint(1) NOT NULL,
  `is_approver` tinyint(1) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `approval_notification_emails` text NOT NULL,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `is_superuser` (`is_superuser`),
  KEY `is_data_profiler` (`is_data_profiler`),
  KEY `is_approver` (`is_approver`),
  KEY `updated_at` (`updated_at`),
  KEY `created_at` (`created_at`),
  KEY `idx_updated_at` (`updated_at`)
) ENGINE=InnoDB CHARSET=utf8mb4;
```

**Comment by zzz686970** [comment]
For those using default sqlite3, below is the sql script to build tables.
```
        CREATE TABLE IF NOT EXISTS `dcmp_dag` (
          `id` int(11) NOT NULL primary key,
          `dag_name` varchar(100) NOT NULL unique,
          `version` int(11) NOT NULL,
          `category` varchar(50) NOT NULL,
          `editing` tinyint(1) NOT NULL,
          `editing_user_id` int(11) DEFAULT NULL,
          `editing_user_name` varchar(100) DEFAULT NULL,
          `last_editor_user_id` int(11) DEFAULT NULL,
          `last_editor_user_name` varchar(100) DEFAULT NULL,
          `updated_at` datetime(6) NOT NULL,
          approved_version int(11) NOT NULL,
          approver_user_id int(11) DEFAULT NULL,
          approver_user_name varchar(100) DEFAULT NULL,
          last_approved_at datetime(6),
          last_edited_at detetime(6),
          editing_start datetime(6)
        ) ;



        CREATE TABLE IF NOT EXISTS `dcmp_user_profile` (
          `id` int(11) NOT NULL PRIMARY KEY,
          `user_id` int(11) NOT NULL,
          `is_superuser` tinyint(1) NOT NULL,
          `is_data_profiler` tinyint(1) NOT NULL,
          `is_approver` tinyint(1) NOT NULL,
          `updated_at` datetime(6) NOT NULL,
          `created_at` datetime(6) NOT NULL,
          approval_notification_emails text NOT NULL
        ) ;



        CREATE TABLE IF NOT EXISTS `dcmp_dag_conf` (
          `id` int(11) NOT NULL PRIMARY KEY ,
          `dag_id` int(11) NOT NULL,
          `dag_name` varchar(100) NOT NULL,
          `action` varchar(50) NOT NULL,
          `version` int(11) NOT NULL,
          `conf` text NOT NULL,
          `creator_user_id` int(11) DEFAULT NULL,
          `creator_user_name` varchar(100) DEFAULT NULL,
          `created_at` datetime(6) NOT NULL,
          approver_user_id int(11) DEFAULT NULL,
          approver_user_name varchar(100) DEFAULT NULL,
          approved_at datetime(6)
        );
```
