### ISSUE TITLE
dcmp.auth.backends.password_auth error

### ISSUE THREAD

**Issue by jet2007** [lattebank/airflow-dag-creation-manager-plugin#7]
settting:
  authenticate = True
  auth_backend = dcmp.auth.backends.password_auth

Error:

Traceback (most recent call last):
  File "/bin/airflow", line 27, in <module>
    args.func(args)
  File "/usr/lib/python2.7/site-packages/airflow/bin/cli.py", line 678, in webserver
    app = cached_app(conf)
  File "/usr/lib/python2.7/site-packages/airflow/www/app.py", line 161, in cached_app
    app = create_app(config)
  File "/usr/lib/python2.7/site-packages/airflow/www/app.py", line 44, in create_app
    airflow.load_login()
  File "/usr/lib/python2.7/site-packages/airflow/__init__.py", line 59, in load_login
    login = import_module(auth_backend)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/airflow/AIRFLOWAPP/plugins/dcmp/auth/__init__.py", line 1, in <module>
    import dcmp.auth.models
  File "/home/airflow/AIRFLOWAPP/plugins/dcmp/auth/models.py", line 77, in <module>
    from dcmp.auth.backends.password_auth import PasswordUser
  File "/home/airflow/AIRFLOWAPP/plugins/dcmp/auth/backends/password_auth.py", line 52, in <module>
    class PasswordUser(models.User):
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/ext/declarative/api.py", line 64, in __init__
    _as_declarative(cls, classname, cls.__dict__)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 88, in _as_declarative
    _MapperConfig.setup_mapping(cls, classname, dict_)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 103, in setup_mapping
    cfg_cls(cls_, classname, dict_)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 133, in __init__
    self._setup_inheritance()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 458, in _setup_inheritance
    (c, cls, inherited_table.c[c.name])
sqlalchemy.exc.ArgumentError: Column 'password' on class <class 'dcmp.auth.backends.password_auth.PasswordUser'> conflicts with existing column 'users.password'

**Comment by kainanbin** [comment]
when i Upgrade database,it has an error:
ERROR - Failed to import plugin /root/airflow/plugins/dcmp/tools/update_superuser.py
